### PR TITLE
Allowing translations of theme and adding Czech translation

### PR DESCRIPTION
**Pull request by rbukovansky**
This allows translations of your theme (which is awesome BTW!) to other languages using languages.yaml file in root directory of this theme.

I'm providing Czech translation of your theme with it as well.

### CODE REVIEW

**Comment by rbukovansky** [comment]
@Perlkonig Any takers?

**Comment by Perlkonig** [comment]
Sorry for the delay. Life is a little chaotic at the moment. Will take a look as soon as I can.

**Comment by Perlkonig** [comment]
Done and tested. New release imminent. Many thanks!

**Comment by rbukovansky** [comment]
@Perlkonig My pleasure, I'm glad to help.

BTW Do you need to do anything to get Grav Admin to pick up there is new version released so it should download update?

And no worries about the delay. I still owe one Swift library update to work proper on Linux like for 2 months. There's so little time for everything...

**Comment by Perlkonig** [comment]
It should have picked it up by now. I'll double check later. The skeleton will take longer for me to update.

**Comment by rbukovansky** [comment]
The update in Grav Admin worked. Thanks.

**Pull request merged**
